### ISSUE TITLE
http://nicevry.site88.net/

### ISSUE THREAD

**Issue by Desiderius77** [Skyline7117/FIREFOX-GPS#1]
Impossible d'y accéder depuis l'Université d'Evry ce matin : 

ERROR
The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: http://nicevry.site88.net/

```
Connection to 31.170.162.63 failed.
```

The system returned: (110) Connection timed out

The remote host or network may be down. Please try the request again.

Your cache administrator is webmaster.

Generated Mon, 01 Feb 2016 08:16:29 GMT by proxy-www--igbi.miage.ibisc.univ-evry.fr (squid/2.7.STABLE9)

**Comment by bouhafs** [comment]
Le site est de nouveau fonctionnel.
